version: "3.7"

services: 
  rentx_database:
    image: postgres
    container_name: rentx_database
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=rentx
      - POSTGRES_DB=rentx
    volumes: 
      - pgdata:/data/postgres
      

  rentx_app:
    build: .
    container_name: rentx_app
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
    depends_on:
      - rentx_database
    links:
      - rentx_database
      
volumes: 
  pgdata: 
    driver: local
